name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --verbosity normal
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Upload
      uses: actions/upload-artifact@v4.3.3
      with:
        name: artifact
        path: /home/runner/work/powershell-modules/powershell-modules/MarleyDJ.Common/bin/Debug/netstandard2.0/
        if-no-files-found: warn
        retention-days: 0
        compression-level: 0
        overwrite: false
          
